name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Or your preferred Node.js version
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test # Skip this step if no tests exist

    - name: Bump version
      run: npm run release

    - name: Publish to npm
      env:
        NPM_AUTH_TOKEN: ${ secrets.NPM_AUTH_TOKEN }
      run: npm publish