name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Or your preferred Node.js version
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org/'

    - name: Set up Git user
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test # Skip this step if no tests exist

    - name: Bump version
      run: npm run release

    - name: Authenticate with npm
      run: npm login --auth-token=${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: npm publish